angstwad/docker.ubuntu

README.md, Vagrantfile, tests/vagrant.yml
Add support for testing the role against Ubuntu LTS releases using Vagrant.
=> Vagrant based test

defaults/main.yml
=> Fixed a typo in defaults/main.yml

README.md
=> Another typo

Vagrantfile
Described in #47, now properly created.
=> Fix for vagrant creating untracked files

README.md, Vagrantfile, defaults/main.yml, tasks/main.yml, tests/vagrant.yml
For sake of merge simplicity, I first packed all this stuff in a single PR, but I am of course open to create dedicated pull requests if you prefer (or don't accept all these changes).
=> Install docker-compose (via pip) and optionally add users to the docker group

defaults/main.yml, tasks/main.yml
It seems the location of this file was changed at 14.04. I'm not sure when, but others have seen it as well. So I created a variable for it so I can make it work with my machines. Best Regards.
=> Added a variable for the defaults file

defaults/main.yml, tasks/main.yml
Using new way of installing docker as per https://blog.docker.com/2015/07/new-apt-and-yum-repos/ to fix #60
=> Fixes #60 : new docker installation

README.md, defaults/main.yml, tasks/main.yml
Feature requested here: https://github.com/angstwad/docker.ubuntu/issues/78
=> flags for preventing pip installs

tasks/main.yml, templates/docker.conf
* According to the official docs files in /usr/lib/systemd/system or
/lib/systemd/system contain the defaults and should not be modified
* The recommended method to configure the daemon is to place files in
/etc/systemd/system/docker.service.d
* https://docs.docker.com/engine/admin/systemd/
=> Update docker daemon configuration file

defaults/main.yml
=> Use long gpg id

tasks/main.yml
=> Only update facts for ansible_docker0

defaults/main.yml
https://docs.docker.com/engine/installation/linux/ubuntulinux/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/angstwad/docker.ubuntu/107)
=> Use keyserver from official docker docs

README.md, Vagrantfile, defaults/main.yml, meta/main.yml, tasks/main.yml
Hi, I added Debian Jessie support. Is there any chance to get this merged? thank you
=> Add support for Debian Jessie #105

tasks/main.yml
As it actually doesn't change anything.
=> Prevent read uname to report changed

tasks/main.yml
Fixes https://github.com/angstwad/docker.ubuntu/issues/146
=> Replace deprecated option

vars/main.yml
The issue will be fixed in Ansible 2.3.0 version.
See: https://github.com/ansible/ansible/commit/e2a1ce2916e9b87fe1ad4a1011c04ef8d2faf046
=> Remove no longer needed TODO

tasks/main.yml
Reverts angstwad/docker.ubuntu#147
=> Revert "Replace deprecated option"

defaults/main.yml, tasks/main.yml, templates/docker.conf
Basically does the work for https://github.com/angstwad/docker.ubuntu/issues/125
=> use daemon.json instead of DOCKER_OPTS

tasks/main.yml
Please refer to commit message for details.
=> Fix error when specifying `daemon_json`

tasks/main.yml
for some reason /etc/docker was not exist on my system. Proposed patch is fixing this problem.
=> add fix to ensure /etc/docker is present

defaults/main.yml
Resolving following:
ERROR [role] ./defaults/main.yml:105:1: [error] too many blank lines (1 > 0) (empty-lines)
=> Remove unwanted empty-line at EOF in main.yml

defaults/main.yml, tasks/main.yml
Added a flag that toggles whether or not this role messes with UFW policy.
=> Added flag to control UFW forward policy

meta/main.yml, tasks/kernel_check_and_update.yml, tasks/main.yml
Justification for commit https://github.com/angstwad/docker.ubuntu/pull/223/commits/c091607dd1f82c9dbf3d5a70b3c616e8a5d46e49 : Issue https://github.com/angstwad/docker.ubuntu/issues/221
Justification for commit https://github.com/angstwad/docker.ubuntu/pull/223/commits/e30627ff8be83f8fe59f009b5f0240cc2939e7d8 : https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-items
=> Pass lists to package modules instead of loops with squash_actions

defaults/main.yml, tasks/main.yml
Installation through proxies
Permit to use optionally those install proxies as the docker daemon proxies
=> Permit to provide proxies for installation
