tasks/main.yml

The kernel installation task on 12.04 wasn't respecting the option and
was always upgrading to latest.

Make kernel install task respect kernel_pkg_state

---

README.md
defaults/main.yml
tasks/main.yml

Generalized and cleaned up setting docker options a bit.
There are various other options that you may want to set apart from specifying additional port to listen on, I think this way may be more readable if you need to do that.

Generalize docker opts

---

tasks/main.yml

When docker_opts is not set it defaults to an empty string which should
just evaluate to False in a boolean context, but for some reason was
failing with:
template error while templating string: Expected an expression, got 'end of statement block'

Fix condition on task setting docker options

---

README.md
defaults/main.yml
tasks/main.yml

PR as discussed in #40 
i needed to duplicate the pip task because version: and state:latest are not compatible. 
the defaults are set to latest.

Add variables for python package versions and set default to latest.

---

tasks/main.yml

I am setting `docker_pkg_name` to `lxc-docker-{version}`

Update condition to allow pkg name with version

---

README.md
defaults/main.yml
tasks/kernel_check_and_update.yml
tasks/main.yml

I don't think it's a good idea. What if you accidentally run this on a production 12.04?
Here's how I solve this for my lxc role:
```
- name: update kernel
include: kernel_check_and_update.yml
when: update_kernel_if_required
```
```update_kernel_if_required``` is set to false in defaults.
Can I make a pull request with such a fix?

Reboot instance is enabled by default

---

README.md
defaults/main.yml

The official docker install-script (https://get.docker.com/ and https://get.docker.com/ubuntu/) now use https://get.docker.com as their base url. This PR reflects that change. 
Using the old url, I ran into problems when doing an apt-get update.

Update default apt_repository variable

---

tasks/main.yml

In the current implementation, the step "Ensure updatedb does not index /var/lib/docker" always returns "changed" even when the contents of the file are not changed. This change modifies that task to act idempotently, thereby fixing the accuracy of the status returned for this task.
**Testing:**
* Ran with the included `Vagrantfile` for ubuntu-12.04 and ubuntu-14.04
* Upon a second invokation of `vagrant provision` I see that the task no longer returned a status of "changed"
```
TASK: [docker.ubuntu | Ensure updatedb does not index /var/lib/docker] ********
<127.0.0.1> REMOTE_MODULE lineinfile line='PRUNEPATHS="/var/lib/docker \2"' state=present regexp='^PRUNEPATHS="(/var/lib/docker )?(.*)"$' dest=/etc/updatedb.conf
ok: [ubuntu-1404] => {"backup": "", "changed": false, "msg": ""}
...
PLAY …
```

Fix idempotence of updating /etc/updatedb.conf

---

README.md
defaults/main.yml
tasks/main.yml

Recent docker update leaded to docker_image module incompatibility. At this point I would like to change default behaviour from ```latest``` to ```present``` and allow setting ```latest``` with a variable. Breaking everything with just a simple playbook run doesn't seem to be nice in production.
Any objections?

docker updates brake api

---

handlers/main.yml
tasks/main.yml

With the introduction of systemd on 15.04, the existing DOCKER_OPTS implementation does not work. This pull request should address that by editing the ExecStart line in the systemd unit, and adding a side-load config file to /etc/systemd/system/docker.service.d/ to include those docker options. Had to refactor the handlers slightly as well as "reloaded" doesn't play nice with systemd, it seems.

Support for DOCKER_OPTS on Ubuntu 15.04

---

tasks/main.yml

On the first run, it's started automatically
But on other runs, it doesn't.
Also even if the service is started already, this won't change the service state.

* Try to start the service `docker` when docker package name includes `docker-engine`

---

README.md
defaults/main.yml
tasks/main.yml

Prior to this change, the "cache_valid_time" arg to the "apt" installation task was hard-coded to 600 seconds. This can slow performance of ansible-playbook runs for folks who do not want their apt-cache updated so frequently.
This change fixes the issue by parameterizing into a new role variable, "docker_apt_cache_valid_time".
Also update the README.md file.

Parameterize "cache_valid_time" for "apt" installation task

---

tasks/main.yml

In #75, I'd parameterized the apt-cache's valid-time for installing "docker-engine", but missed the parameterization of the apt-cache valid time for installing python-dev & python-pip. This change fixes that omission.
Adding this because it will allow the playbook runs to complete faster, without unnecessary "apt-get update"s.
Thanks!

Use "docker_apt_cache_valid_time" for installing python-dev & python-pip

---

docker.yml
tasks/kernel_check_and_update.yml
tests/vagrant.yml

I kept getting this message:
```
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make 
sure become_method is 'sudo' (default). This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```
So I fixed it.

Fixed deprecation warning message

---

tasks/main.yml

Alternative add-key task curl'ed the key from wrong location `https://get.docker.com/gpg`. 
Correct one is `https://apt.dockerproject.org/gpg`, which is defined as `apt_key_url` variable and correctly used during the primary add-key task.

Fix outdated key in alternative key-add task

---

handlers/main.yml
tasks/main.yml

Fix for issue #89
state=reloaded doesn't actually have any effect on a running
docker process in ubuntu 14.04. In particular, the /etc/init.d/docker
start script does not execute, so any customised storage options will
not be applied to the running docker process which may result in
a big surprise when the daemon is eventually restarted and images
added to the loopback thin pool device are no longer accessible in
the configured thinpool device.
This change removes the "Reload docker" handler and changes the pre 15.04
handler to use "Restart docker" instead.

Restart rather than reload docker.

---

tasks/main.yml

Otherwise "Add Docker repository and update apt cache" step fails with
"E: The method driver /usr/lib/apt/methods/http could not be found."

Install apt-transport-https

---

tasks/main.yml

It could cause error 
> ifstream::ifstream (13: Permission denied)
in some tasks.

Set repository file mode 644, as system default

---

tasks/main.yml

It's better to use keyserver instead of url in apt_key module, because defining an url will perform an HTTP request to get the key, whereas defining a keyserver will perform a request to get a specific key from that server (possibly using some other protocol). For example, currently docker documentation uses hkp://p80.pool.sks-keyservers.net:80 that will not work with url, but will work good with keyserver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/angstwad/docker.ubuntu/106)

Use keyserver when adding rero key

---

defaults/main.yml
tasks/kernel_check_and_update.yml
tasks/main.yml

Otherwise dpkg cannot install docker (installation hangs)
See details here: https://github.com/docker/docker/issues/23347

Ubuntu 16.04 requires dmsetup to be installed before docker.

---

tasks/main.yml

Required for AuFS - without it our boxes lockup.
Fixes https://github.com/angstwad/docker.ubuntu/issues/115

Add necessary linux-image-extra-* apt packages

---

tasks/main.yml

Need to do a version check before installing `linux-image-extra-` packages as per:
https://docs.docker.com/engine/installation/linux/ubuntulinux/
Fixes #123

Check ubuntu version before installing linux-image-extra-

---

README.md
defaults/main.yml
tasks/main.yml

WiP
In an old/closed PR comment, I gave different proposals on howto make this more configurable:
https://github.com/angstwad/docker.ubuntu/pull/25#issuecomment-265760460
Notes:
* proposal (1) is already outdated, after my latest fixes.
* proposal (2) can be improved:
```
docker_http_proxy_enabled: false
docker_http_proxy: "{{ docker_http_proxy_enabled | ternary(ansible_env.http_proxy|default(''), '') }}"
docker_https_proxy: "{{ docker_http_proxy_enabled | ternary(ansible_env.https_proxy|default(''), '') }}"
docker_https_proxy: "{{ansible_env.https_proxy | default('') }}"
```
Note: the general `docker_http_proxy_enabled` var could still be useful  (to set to 'true' and the 2 other vars to 'empty string') to disable existing HTTP(S)_PROXY (by setting the same env-vars to empty ('') values)

Configurable proxy in the docker config

---

tasks/main.yml

dmsetup_result is a non empty dictionary, it will always be evaluated
to True.

Fix dmsetup run condition

---

tasks/main.yml

To prevent tasks from reporting changed when nothing has actually changed.
It also speeds up deployment when caches don't require to be updated.

Update caches only when required

---

tasks/main.yml

Only run dmsetup mknodes if dmsetup install is not skipped

---

tasks/main.yml

Otherwise the 'Install linux-image-extra-* packages' task fails in check
mode as it uses the result of the read uname task.

Run the read uname task even in check mode

---

tasks/main.yml
vars/main.yml

docker-compose > 1.10 requires the docker python package which is
incompatible with the docker_container module in Ansible < 2.3.
This fixes #135.

Handle docker-compose version

---

tasks/main.yml

Python's `rstrip` function calls were not stripping whitespace from the role's `docker_opts` option. This caused the created file at `/etc/systemd/system/docker.service.d/env.conf` to have an extra line, like so:
```
[Service]
Environment="DOCKER_OPTS=--graph=/data-01/.docker-data
"
```
The options were then not loaded properly by the Docker daemon.
This PR removes _all_ whitespace from the end of the `docker_opts` setting, which removes the extra line (as well as any other whitespace, which should not be needed).
```
Local:
Python 2.7.12
ansible 2.0.1.0
Remote:
Ubuntu 16.04 on EC2
Linux ip-10-0-1-80 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

remove all trailing whitespace from custom docker options config

---

vars/main.yml

This is broken in (unreleased) Ansible 2.3 still.

Change ansible version check

---

vars/main.yml

Comparison has to been done over _pip_version_docker not over
pip_version_docker.

Fix pip docker package name computation

---

vars/main.yml

I discovered an issue with the `version_compare` when running this role via Ansible 2.3 on Ubuntu 12.04. It seems that the interpreter can get confused in the tightly packed vars, so I broke out version comparators into their own vars. This seems to have fixed the issue.

Unpack vars to correct version_compare issue

---

tasks/main.yml

Solves the first part of #178. Still doesn't solve the issue of not having `curl`, but if you've got `gnupg-curl` you shouldn't have to touch that task.

Adding GNUPG-curl verification to role.

---

defaults/main.yml
tasks/main.yml

A defence in depth solution for the naming of packages (especially as this step was necessary for the role to work on Ubuntu 17.04). This keeps the default package but allows user override should they need to use `gnupg2` or `gnupg1-curl` to complete installation.

Make gnupg_curl a variable

---

README.md
Vagrantfile
meta/main.yml
tasks/main.yml

Everything except gnupg-curl works well on Debian Stretch. This add a minimal if-clause for gnupg-curl support.

Add support for Debian Stretch (9)

---

Vagrantfile
defaults/main.yml
tasks/main.yml
tests/vagrant.yml

Closes #189
* right handling "empty" values of docker_http(s)_proxy
* remove http(s)_proxy environment vars if these vars exists after previous installation or manual changes
* minor updates in Vagrantfile

Fixed docker_http(s)_proxy behavior

---

defaults/main.yml
tasks/main.yml

I made some changes that deviated slightly from the official docker install instructions, specifically with regards to the apt-key installation. There is, I think a better way to execute it that works more consistently between Debian & Ubuntu and doesn't require gnupg-curl to make that happen. I also changed key servers because during testing I was getting intermittent failures using the docker keyserver. The server I have in there now is, IIRC the server that used to be in their own install script and hasn't produced any failures. At some point in the future, adding a fallback mode with the docker server or vice-versa to obtain the key is probably a good idea. 
I removed the workaround for dmsetup because that issue was resolved docker side with an update. 
I spun up several VMs for …

Fix for #175 & other changes

---

defaults/main.yml
tasks/main.yml

* Add flush handler at the end of main, this is to allow config options
to be picked up once the role has finished. In my case setting proxies
and bridge ip. Without this line it requires two Ansible runs due to
nature of handlers.
* Added configurable option for bridge ip. By default it conflicts with
my ip schema. This is now a configurable option.

Flush fixes and adjustment to default bridge ip option

---

defaults/main.yml
handlers/main.yml
tasks/main.yml

I have some servers which only have docker installed but no docker daemon running. They are only used to controll other docker hosts using docker-machine.
The systemd docker deamon is masked to prevent the dockerd from running accidently. This leads to errors wich this ansible playbook since a couple of days.
That do you think about this PR ? It helps me to run the playbook successfully on all my hosts again.

add var start_docker_daemon to only (re)start docker daemon if it is true

---

defaults/main.yml
tasks/main.yml

This has the potential to overwrite the the `daemon.json` file if `docker_bip` is set, which is not ideal for obvious reasons. 
Setting `bip` attribute on the `daemon_json` object should be enough to solve for this issue.  An additional flush handlers could be added in the future if necessary. 
Reverts angstwad/docker.ubuntu#203

Revert "Flush fixes and adjustment to default bridge ip option"

---

defaults/main.yml

This allows installation of nightly or edge releases without having to override the entire `apt_repository` variable.

Allow selection of apt channel

---

tasks/main.yml

This commit fixes the no_proxy env variable for non systemd versions (there was no task to set it) and treats no_proxy like http_proxy and https_proxy.
While the role could include some logic to automatically omit no_proxy configuration if neither http_proxy nor http_proxy are defined, I think that this choice should be left to the user.

Treating no_proxy as http_proxy and https_proxy

---

tasks/kernel_check_and_update.yml
tasks/main.yml
vars/main.yml

Change all Jinja filter tests to new format:
https://docs.ansible.com/ansible/2.5/porting_guides/porting_guide_2.5.html#deprecated
It should be backwards compatible.

Prepare for Ansbile 2.5 deprecations

---

tasks/main.yml

When using the linux-aws kernel package for EC2 instances, there are no
linux-image-extra packages. However, the kernel image package itself already
contains AuFS support, so the installation can just be skipped.

Handle Ubuntu 14.04 w/ linux-aws kernel package

---

defaults/main.yml
tasks/main.yml

The docker-ce package depends on docker-ce-cli unconstrained, this
can lead to problems where the cli package is too new to communicate
with the daemon. This patch adds an explicit install task for the
cli package, so that it's version can be overridden if necessary.
Related conjurinc/ops#569

Explicitly install cli package
